[project]
name = "api-gateway-back"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "grpcio>=1.70.0",
    "grpcio-tools>=1.70.0",
    "psycopg2-binary>=2.9.10",
    "python-dotenv>=1.0.1",
    "sqlalchemy>=2.0.40",
    "sqlalchemy-cratedb>=0.41.0",
    "uvicorn>=0.34.2",
]
